export const routes = {
    home: '/',
    login: '/auth/login',
    register: '/auth/register',
    forgetPassword: '/auth/forget-password',
    products: '/products',
    categories: '/categories',
    cart: '/cart',
    wishlist: '/wishlist',
    profile: '/profile',
    checkout: '/checkout',
    orders: '/orders',
    settings: '/settings',
    logout: '/logout',
    contact: '/contact',
    about: '/about',
}